// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjFe56xfI5uaYmfnX0vlVOEqe0rjkWj10',
    appId: '1:430221940539:web:4caa4ffd05f7ab8758891e',
    messagingSenderId: '430221940539',
    projectId: 'tasbih-app-flutter',
    authDomain: 'tasbih-app-flutter.firebaseapp.com',
    storageBucket: 'tasbih-app-flutter.firebasestorage.app',
    measurementId: 'G-4QHHLZZR4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCieObgOoDC-70u0B7rbnpTo3PPxPBsc2A',
    appId: '1:430221940539:android:12c97d317918620958891e',
    messagingSenderId: '430221940539',
    projectId: 'tasbih-app-flutter',
    storageBucket: 'tasbih-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1bRIwd1k2lU_nroI4wW9VMSPBZM99yKM',
    appId: '1:430221940539:ios:43105ce9a844a2ad58891e',
    messagingSenderId: '430221940539',
    projectId: 'tasbih-app-flutter',
    storageBucket: 'tasbih-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.moneyManagementFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1bRIwd1k2lU_nroI4wW9VMSPBZM99yKM',
    appId: '1:430221940539:ios:43105ce9a844a2ad58891e',
    messagingSenderId: '430221940539',
    projectId: 'tasbih-app-flutter',
    storageBucket: 'tasbih-app-flutter.firebasestorage.app',
    iosBundleId: 'com.example.moneyManagementFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjFe56xfI5uaYmfnX0vlVOEqe0rjkWj10',
    appId: '1:430221940539:web:23a0e54358c3baa358891e',
    messagingSenderId: '430221940539',
    projectId: 'tasbih-app-flutter',
    authDomain: 'tasbih-app-flutter.firebaseapp.com',
    storageBucket: 'tasbih-app-flutter.firebasestorage.app',
    measurementId: 'G-J9BW7RYRHN',
  );
}
